---
- name: "Provision a new storage group"
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
  - vars.yml

  vars:
    input: &uni_connection_vars
      array_id: "{{ array_id }}"
      password: "{{ password }}"
      unispherehost: "{{ unispherehost }}"
      universion: "{{ universion }}"
      user: "{{ user }}"
      verifycert: "{{ verifycert }}"

    sg_name: "Ansible_SG_testing"
    new_sg_name: "New_Ansible_SG_testing"

    lun_request:
      # Each item will be treated as a request for volumes, all sizes are GB
      # values. A request can have multiple volumes with the same name,
      # however module will kept only the last vol_name for labeling. This
      # is self imposed restriction to make idempotence easier for change
      # tracking.
      - num_vols: 1
        cap_gb: 2
        vol_name: "DATA"
      - num_vols: 1
        cap_gb: 1
        vol_name: "REDO"

    lun_addon:
      # This request will be used later for "adding only" scenario by
      # merging it with the initial request
      - num_vols: 1
        cap_gb: 2
        vol_name: "NEW_DATA"


  tasks:
    - name: Create new empty Storage Group
      dellemc_pmax_storagegroup:
        <<: *uni_connection_vars
        sgname: "{{ sg_name }}"
        slo: "Diamond"
        state: "present"
    - debug: var=storagegroup_detail

    - name: "(Idempotency check) Create new empty Storage Group"
      dellemc_pmax_storagegroup:
        <<: *uni_connection_vars
        sgname: "{{ sg_name }}"
        slo: "Diamond"
        state: "present"
    - debug: var=storagegroup_detail

    - name: "Switch Off compression"
      dellemc_pmax_storagegroup:
        <<: *uni_connection_vars
        sgname: "{{ sg_name }}"
        compression: false
        slo: "Diamond"
        state: "present"
    - debug: var=storagegroup_detail

    - name: "Switch back On compression"
      dellemc_pmax_storagegroup:
        <<: *uni_connection_vars
        sgname: "{{ sg_name }}"
        compression: true
        slo: "Diamond"
        state: "present"
    - debug: var=storagegroup_detail

    - name: Adding volumes to this Storage Group
      dellemc_pmax_storagegroup:
        <<: *uni_connection_vars
        sgname: "{{ sg_name }}"
        slo: "Diamond"
        luns: "{{ lun_request }}"
        state: "present"
    - debug: var=storagegroup_detail

    - name: "(Idempotency check) Adding volumes to this Storage Group"
      dellemc_pmax_storagegroup:
        <<: *uni_connection_vars
        sgname: "{{ sg_name }}"
        slo: "Diamond"
        luns: "{{ lun_request }}"
        state: "present"
    - debug: var=storagegroup_detail

    # It's possible to append only volumes to an existing SG (without
    # specifying the whole LUN list) by getting vars of this SG
    # (storagegroup_detail) first and then merge it with your request

    - name: "Adding volumes just a few volumes to this Storage Group"
      dellemc_pmax_storagegroup:
        <<: *uni_connection_vars
        sgname: "{{ sg_name }}"
        slo: "Diamond"
        luns: "{{ storagegroup_detail.lun_request + lun_addon }}"
        state: "present"
    - debug: var=storagegroup_detail

    - name: "Renaming Storage Group from {{ sg_name }} to {{ new_sg_name }}"
      dellemc_pmax_storagegroup:
        <<: *uni_connection_vars
        sgname: "{{ sg_name }}"
        new_sgname: "{{ new_sg_name }}"
        slo: "Diamond"
        state: "present"
    - debug: var=storagegroup_detail

    - name: Deleting Storage Group only volumes will be not deleted
      dellemc_pmax_storagegroup:
        <<: *uni_connection_vars
        sgname: "{{ new_sg_name }}"
        slo: "Diamond"
        state: "absent"
    - debug: var=storagegroup_detail

    - name: "(Idempotency) Deleting Storage Group only volumes will be not deleted"
      dellemc_pmax_storagegroup:
        <<: *uni_connection_vars
        sgname: "{{ new_sg_name }}"
        slo: "Diamond"
        state: "absent"
    - debug: var=storagegroup_detail

