- name: "Create a New Port Group"
  connection: local
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: "Create New Port Group and add ports"
      dellemc_pmax_portgroup:
             unispherehost: "{{unispherehost}}"
             universion: "{{universion}}"
             verifycert: "{{verifycert}}"
             user: "{{user}}"
             password: "{{password}}"
             array_id: "{{array_id}}"
             portgroup_id: "Ansible_PG"
             array_ports:
               -  FA-2D:8
               -  FA-1D:8
             state: present
             port_state: in_pg
